name: Run compose screenshots

on:
  push

jobs:
  compose-screenshot:
    environment: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Load Google Service json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES | base64 --decode > application/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update Screen Shot test with Gradle
        run: ./gradlew :ui:updateDebugScreenshotTest

      - name: Commit and push images
        run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m 'Updated compose screen shot tests'
            git push
